# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smush', '0003_auto_20160610_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='tmp_files'),
        ),
    ]
